### ISSUE TITLE
Support for patches

### ISSUE THREAD

**Issue by Alistair1231** [JulianGi/IGGScraper#5]
Hey!
First of, thanks so much! 
Finally I can use igg again :)

Script seems to work great, but it doesn't grab the patch links. 
e.g. 
https://igg-games.com/kingdom-come-982135947-deliverance-free-download.html
hast 15 links and 6 updates. the script only gets the 15 links.

I would love support for those patches as well. 

Right now I just used [this](https://greasyfork.org/en/scripts/423435-igg-games-bluemediafiles-bypass/) script, which you took some code from for your script but it would be much nicer if I wouldn't need two steps

Also minor thing but support for usage like this:
`python .\igg_scraper.py --provider rapidgator https://igg-games.com/kingdom-come-982135947-deliverance-free-download.html`
would be great :)

**Comment by JulianGi** [comment]
Fixed in 5afe1c0eb33088d9629313f3e97b6eb4a96c34eb. You can open another issue for you feature request. I will get to it when I can
